# Generated by Django 5.1.3 on 2024-11-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('cep', models.IntegerField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('cd_especialidade', models.IntegerField(primary_key=True, serialize=False)),
                ('especialidade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('cd_exame', models.IntegerField(primary_key=True, serialize=False)),
                ('exame', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('crm', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_nascimento', models.DateTimeField()),
                ('medico', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tb_modulo',
            fields=[
                ('cd_modulo', models.IntegerField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tb_perfil',
            fields=[
                ('cd_perfil', models.IntegerField(primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tb_usuario',
            fields=[
                ('senha', models.CharField(max_length=10)),
                ('usuario', models.CharField(max_length=10)),
                ('cd_usuario', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('cnpj', models.IntegerField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=10)),
                ('nome_fantasia', models.CharField(max_length=10)),
                ('cep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='EntAssoss2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.clinica')),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.medico')),
            ],
        ),
        migrations.CreateModel(
            name='EntAssoss1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.especialidade')),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Rl_perfil_modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.tb_modulo')),
                ('cd_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.tb_perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Rl_perfil_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.tb_perfil')),
                ('cd_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.tb_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('cd_agendamento', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.clinica')),
                ('cd_especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.especialidade')),
                ('cd_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.exame')),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.medico')),
                ('cd_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.tb_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.IntegerField(primary_key=True, serialize=False)),
                ('chat', models.CharField(max_length=10)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.clinica')),
                ('cd_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agende.tb_usuario')),
            ],
        ),
    ]
