# Generated by Django 5.1.3 on 2024-11-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agende', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='entassoss2',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='cd_especialidade',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='cd_exame',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='cd_usuario',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='entassoss1',
            name='cd_especialidade',
        ),
        migrations.RemoveField(
            model_name='entassoss1',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='entassoss2',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='rl_perfil_modulo',
            name='cd_modulo',
        ),
        migrations.RemoveField(
            model_name='rl_perfil_modulo',
            name='cd_perfil',
        ),
        migrations.RemoveField(
            model_name='rl_perfil_usuario',
            name='cd_perfil',
        ),
        migrations.RemoveField(
            model_name='rl_perfil_usuario',
            name='cd_usuario',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Clinica',
        ),
        migrations.DeleteModel(
            name='Exame',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Especialidade',
        ),
        migrations.DeleteModel(
            name='EntAssoss1',
        ),
        migrations.DeleteModel(
            name='EntAssoss2',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='Tb_modulo',
        ),
        migrations.DeleteModel(
            name='Rl_perfil_modulo',
        ),
        migrations.DeleteModel(
            name='Tb_perfil',
        ),
        migrations.DeleteModel(
            name='Rl_perfil_usuario',
        ),
        migrations.DeleteModel(
            name='Tb_usuario',
        ),
    ]
