# Generated by Django 5.1.3 on 2025-02-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agende', '0006_remove_clinica_latitude_remove_clinica_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinica',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
